server.servlet.context-path=/inventory
server.port=9010


#DB Connections
spring.datasource.url=jdbc:postgresql://localhost:5432/inventoryDB
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.datasource.username=postgres
spring.datasource.password=1001

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.web=DEBUG
management.endpoints.web.exposure.include=*

spring.jpa.defer.datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql


spring.jpa.open-in-view=false


#eureka config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
